services:
  obsidian:
    image: obsidian
    container_name: obsidian

    volumes:
      # The actual Obsidian vault
      - /opt/obsidian/vault:/vault

      # Persist Obsidian headless authentication/config
      - /opt/obsidian/config:/home/node/.config

    command:
      - sync
      - --path
      - /vault
      - --continuous

    restart: unless-stopped

  opencode:
    image: opencode_golang
    container_name: opencode

    command:
      - serve
      - --hostname
      - "0.0.0.0"
      - --port
      - "4096"

    depends_on:
      - obsidian

    environment:
      OPENCODE_SERVER_PASSWORD: ${OPENCODE_SERVER_PASSWORD}

    volumes:
      - /opt/opencode/workspace:/workspace
      - /opt/opencode/config:/home/opencode/.config/
      - ./:/home/opencode/.config/opencode
      - /opt/opencode/local:/home/opencode/.local/
      - /opt/obsidian/vault:/vault
      - /opt/opencode/worktrees:/worktrees

    expose:
      - "4096"

    restart: unless-stopped


  openchamber:
    image: openchamber
    container_name: openchamber

    depends_on:
      - opencode

    ports:
      - "3000:3000"

    environment:
      OPENCHAMBER_UI_PASSWORD: ${OPENCHAMBER_UI_PASSWORD}
      OPENCODE_SERVER_PASSWORD: ${OPENCODE_SERVER_PASSWORD}

    volumes:
      - /opt/openchamber/config:/home/node/.config/
      - ${HOME}/.ssh/id_ed25519:/home/node/.ssh/id_ed25519:ro
      - ${HOME}/.ssh/id_ed25519.pub:/home/node/.ssh/id_ed25519.pub:ro
      - ${HOME}/.ssh/known_hosts:/home/node/.ssh/known_hosts:ro
      - /opt/opencode/workspace:/workspace
      - /opt/opencode/worktrees:/worktrees
        #- ./:/workspace/code/github.com/gwagner/endpoint-observer/.opencode/

    restart: unless-stopped
